version: "3.9"

services:
  pecai:
    container_name: pecai_server
    image: pecai
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - "../models:/app/models"
    # platform: linux/amd64
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: ./deployments/travel/Dockerfile
    env_file:
      - ./.env
    networks:
      - network
    stop_signal: SIGINT
    stop_grace_period: 15s
    restart: unless-stopped

  neo4j:
    image: neo4j:5.18.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./neo4j_data:/data"
      - "./neo4j_plugins:/plugins"
      - "./neo4j_conf:/conf/"
    environment:
      - NEO4J_AUTH=neo4j/qwertyqwerty
      - NEO4J_apoc_export_file_enabled=true 
      - NEO4J_apoc_import_file_enabled=true 
      - NEO4J_apoc_import_file_use__neo4j__config=true 
      - NEO4J_PLUGINS="\[\"apoc\"\]" 
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge
